name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the default branch of your repo
permissions:
  contents: write
  pages: write  # If you're using a custom branch for GitHub Pages, ensure to add this.

jobs:

  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'  # Set this to the node version you are using

    - name: Install Dependencies
      run: yarn install

    - name: Build Project
      run: yarn run build

    - name: Copy public folder to assets
      run: |
        mkdir -p dist/assets
        cp -R public/* dist/assets/

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        branch: gh-pages  # The branch the action should deploy to.
        folder: dist      # The folder the action should deploy.
        clean: false       # Automatically remove deleted files from the deployment